apiVersion: v1
data:
  telegraf.conf: |
    [global_tags]
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      debug = false
      quiet = false
      logfile = ""
      hostname = ""
      omit_hostname = false
    [[outputs.prometheus_client]]
      listen = "0.0.0.0:9273"
      expiration_interval = "0"
    [[inputs.logparser]]
      files = ["/var/log/mysql/slow.log"]
      from_beginning = false
      [inputs.logparser.grok]
        patterns = ['# Query_time: %{NUMBER:query}\s+Lock_time: %{NUMBER:lock_wait} Rows_sent: %{NUMBER:row_sent}\s*Rows_examined: %{NUMBER:rows_examined}']
        measurement = "slow_logs"
kind: ConfigMap
metadata:
  annotations:
  name: telegraf-config
  namespace: default